#spring.application.name=Task1
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:task1
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.show-sql=true
spring:
  application:
    name: Task1

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:task1
    driver-class-name: org.h2.Driver
    show-sql: true

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          #iss from jwt.io
          issuer-uri: https://dev-plbflltsnuuohk2n.us.auth0.com/
          #aud from jwt.io
          audiences:
            - https://customerapi
            - https://projectapi
            - https://employeeapi